<?php
$data = array(
    array("artist"=>"Prince","album"=>"Purple Rain","number"=>"0","decade"=>"80s","count"=>1,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Michael Jackson","album"=>"Thriller","number"=>"1","decade"=>"80s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Journey","album"=>"Escape","number"=>"2","decade"=>"80s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Bon Jovi","album"=>"Slippery When Wet","number"=>"3","decade"=>"80s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Guns N' Roses","album"=>"Appetite for Destruction","number"=>"4","decade"=>"80s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Michael Jackson","album"=>"Bad","number"=>"5","decade"=>"80s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Cyndi Lauper","album"=>"She's So Unusual","number"=>"6","decade"=>"80s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Janet Jackson","album"=>"Rhythm Nation 1814","number"=>"7","decade"=>"80s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Def Leppard","album"=>"Hysteria","number"=>"8","decade"=>"80s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Paula Abdul","album"=>"Forever Your Girl","number"=>"9","decade"=>"80s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Lionel Richie","album"=>"Can't Slow Down","number"=>"Mashup","decade"=>"80s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Madonna","album"=>"True Blue","number"=>"Air Horn","decade"=>"80s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Tina Turner","album"=>"Private Dancer","number"=>"Scratch","decade"=>"80s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Eminem","album"=>"The Slim Shady LP","number"=>"0","decade"=>"90s","count"=>1,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Janet Jackson","album"=>"janet.","number"=>"1","decade"=>"90s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Madonna","album"=>"Erotica","number"=>"2","decade"=>"90s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Michael Jackson","album"=>"Dangerous","number"=>"3","decade"=>"90s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"TLC","album"=>"CrazySexyCool","number"=>"4","decade"=>"90s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Lauryn Hill","album"=>"The Miseducation of Lauryn Hill","number"=>"5","decade"=>"90s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Seal","album"=>"Seal","number"=>"6","decade"=>"90s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Whitney Houston","album"=>"My Love is Your Love","number"=>"7","decade"=>"90s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Duran Duran","album"=>"Duran Duran","number"=>"8","decade"=>"90s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Destiny's Child","album"=>"The Writing's On the Wall","number"=>"9","decade"=>"90s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Cher","album"=>"Believe","number"=>"Mashup","decade"=>"90s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Spice Girls","album"=>"Spice","number"=>"Air Horn","decade"=>"90s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Mariah Carey","album"=>"Daydream","number"=>"Scratch","decade"=>"90s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Radiohead","album"=>"Kid A","number"=>"0","decade"=>"2000s","count"=>1,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Eminem","album"=>"The Marshall Mathers LP","number"=>"1","decade"=>"2000s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"OutKast","album"=>"Stankonia","number"=>"2","decade"=>"2000s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"The Strokes","album"=>"Is This It","number"=>"3","decade"=>"2000s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Kanye West","album"=>"The College Dropout","number"=>"4","decade"=>"2000s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Amy Winehouse","album"=>"Back to Black","number"=>"5","decade"=>"2000s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Green Day","album"=>"American Idiot","number"=>"6","decade"=>"2000s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Coldplay","album"=>"A Rush of Blood to the Head","number"=>"7","decade"=>"2000s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"The White Stripes","album"=>"Elephant","number"=>"8","decade"=>"2000s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"The Killers","album"=>"Hot Fuss","number"=>"9","decade"=>"2000s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Justin Timberlake","album"=>"FutureSex/LoveSounds","number"=>"Mashup","decade"=>"2000s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"50 Cent","album"=>"Get Rich or Die Tryin'","number"=>"Air Horn","decade"=>"2000s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"MGMT","album"=>"Oracular Spectacular","number"=>"Scratch","decade"=>"2000s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Arcade Fire","album"=>"The Suburbs","number"=>"0","decade"=>"2010s","count"=>1,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Bon Iver","album"=>"Bon Iver, Bon Iver","number"=>"1","decade"=>"2010s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Kendrick Lamar","album"=>"Good Kid, M.A.A.D. City","number"=>"2","decade"=>"2010s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Vampire Weekend","album"=>"Modern Vampires of the City","number"=>"3","decade"=>"2010s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"The War on Drugs","album"=>"Lost in the Dream","number"=>"4","decade"=>"2010s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Kendrick Lamar","album"=>"To Pimp a Butterfly","number"=>"5","decade"=>"2010s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Radiohead","album"=>"A Moon Shaped Pool","number"=>"6","decade"=>"2010s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Kendrick Lamar","album"=>"DAMN.","number"=>"7","decade"=>"2010s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Janelle Monáe","album"=>"Dirty Computer","number"=>"8","decade"=>"2010s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Ariana Grande","album"=>"Sweetener","number"=>"9","decade"=>"2010s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Kanye West","album"=>"My Beautiful Dark Twisted Fantasy","number"=>"Mashup","decade"=>"2010s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Frank Ocean","album"=>"Blonde","number"=>"Air Horn","decade"=>"2010s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Daft Punk","album"=>"Random Access Memories","number"=>"Scratch","decade"=>"2010s","count"=>2,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"R. Kelly","album"=>"Ignition - Remix","number"=>"Remix","decade"=>"WILD","count"=>4,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null),
    array("artist"=>"Diddy","album"=>"No Way Out","number"=>"Remix - Four","decade"=>"WILD","count"=>4,"primaryColor"=>null,"secondaryColor"=>null,"@art"=>null)
  );
